---
title: "Predicting Exoplanet Counts"
author: "James Brainard"
subtitle: "subtitle"
format: 
  html:
    embed-resources: true
---

```{r setup, include=FALSE}
# Would include this chunk at beginning of report.
# Prevents code, warnings (important when loading tidyverse), and messages from outputting
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
```


```{r}
data <- read.csv("data/exoplanet_data.csv", skip = 322)
```

```{r}

```

Maybe helpful for describing variables:

+---------------+-----------------------------------------------------------------------------+
| Variable      | Description                                                                 |
+===============+=============================================================================+
| `mpg`         | Miles/(US) gallon                                                           |
+---------------+-----------------------------------------------------------------------------+
| `cyl`         | Number of cylinders                                                         |
+---------------+-----------------------------------------------------------------------------+
| `wt`          | Weight (1000 lbs)                                                           |
+---------------+-----------------------------------------------------------------------------+
| `vs`          | Engine (0 = V-shaped, 1 = straight)                                         |
+---------------+-----------------------------------------------------------------------------+